'use strict';

module.exports = {
  name: 'mock-services',
  version: require('../package').version,
  host: '0.0.0.0',
  port: 8480,
  dns: {
    enabled: true,
    port: 8453,
    nameservers: [
      '8.8.8.8',
      '1.1.1.1',
    ],
    records: {
      A: { 'devlocal': '127.0.0.1' },
      AAAA: { 'devlocal': '::1' },
      CNAME: { 'mydevlocal': 'devlocal' },
      MX: {
        devlocal: {
          preference: 10,
          exchange: 'mail.devlocal',
        },
      },
      NS: { 'devlocal': '127.0.0.1' },
      PTR: { '127.0.0.1': 'devlocal' },
      SRV: {
        '_mock-services._tcp.devlocal': {
          port: '8480',
          target: 'devlocal',
          priority: 10,
          weight: 5,
        },
      },
      TXT: { 'devlocal': 'mock-services' },
    },
    ttl: 300,
    api: 'dns-proxy-7e84f18a0719',
    cache: {
      ttl: 300000,
      reap: 10000,
    },
  },
  geoip: {
    enabled: true,
    requireAuth: false,
    keys: [ '02o5cjNan5g7AkLtyCtC5g==' ],
    records: {
      '1.1.1.1': {
        country: 'Australia',
        countryCode: 'AU',
        region: 'QLD',
        regionName: 'Queensland',
        city: 'South Brisbane',
        zip: '4101',
        lat: -27.4766,
        lon: 153.0166,
        timezone: 'Australia/Brisbane',
        isp: 'Cloudflare, Inc',
        org: 'APNIC and Cloudflare DNS Resolver project',
        as: 'AS13335 Cloudflare, Inc.',
      },
      '8.8.8.8': {
        country: 'United States',
        countryCode: 'US',
        region: 'VA',
        regionName: 'Virginia',
        city: 'Ashburn',
        zip: '20149',
        lat: 39.03,
        lon: -77.5,
        timezone: 'America/New_York',
        isp: 'Google LLC',
        org: 'Google Public DNS',
        as: 'AS15169 Google LLC',
      },
      '172.217.12.132': { // www.google.com
        country: 'United States',
        countryCode: 'US',
        region: 'NY',
        regionName: 'New York',
        city: 'New York',
        zip: '10123',
        lat: 40.7128,
        lon: -74.006,
        timezone: 'America/New_York',
        isp: 'Google LLC',
        org: 'Google LLC',
        as: 'AS15169 Google LLC',
      },
    },
    fallbacks: {
      '/^(10\\.\\d+\\.\\d+\\.\\d+|192\\.168\\.\\d+\\.\\d+)$/': {
        status: 'fail',
        message: 'private range',
      },
      '/.*/': {
        country: 'United States',
        countryCode: 'US',
        region: 'MA',
        regionName: 'Massachusetts',
        city: 'Boston',
        zip: '02199',
        lat: 42.3487,
        lon: -71.0825,
        timezone: 'America/New_York',
        isp: 'MockServices',
        org: 'MockServices',
        as: 'AS401309 MockServices.',
      },
    },
  },
  logs: {
    level: 'info',
    console: true,
    combined: 'mock-services.log',
    error: 'error.log',
  },
  sendgrid: {
    enabled: true,
    allowUnauthorized: true,
    smtpPort: 8425,
    behaviors: {
      reject: '+should+reject+',
      drop: '+should+drop+',
      bounce: '+should+bounce+',
      defer: '+should+defer+',
      open: '+should+open+',
      click: '+should+click+',
      unsubscribe: '+should+unsubscribe+',
      spam: '+should+spam+',
    },
    webhooks: {
      delay: 250,
      concurrency: 1,
    },
    users: [
      {
        name: 'Default',
        username: 'a28286383674d872787a8807',
        password: 'c8965c3f05e66f325b055db6',
        domains: [ '*' ],
        webhooks: [ ],
      },
    ],
  },
  stripe: {
    enabled: true,
    apiVersion: '2017-06-05',
    livemode: false,
    webhooks: {
      concurrency: 1,
      delay: 0,
    },
    organizations: [
      {
        name: 'Default Organization',
        keys: {
          secret: 'sk_test_a28286383674d872787a8807',
          publishable: 'pk_test_c8965c3f05e66f325b055db6',
        },
        plans: [
          {
            amount: '500',
            interval: 'year',
            name: 'Default Yearly',
            currency: 'usd',
            statement_descriptor: 'Default Yearly Plan',
            id: 'DEFAULT_YEARLY',
          },
        ],
      },
    ],
  },
  webhook: { enabled: true },
};
