'use strict';

module.exports = {
  '/^(10\\.\\d+\\.\\d+\\.\\d+|192\\.168\\.\\d+\\.\\d+)$/': {
    status: 'fail',
    message: 'private range',
  },
  '1.1.1.1': {
    country: 'Australia',
    countryCode: 'AU',
    region: 'QLD',
    regionName: 'Queensland',
    city: 'South Brisbane',
    zip: '4101',
    lat: -27.4766,
    lon: 153.0166,
    timezone: 'Australia/Brisbane',
    isp: 'Cloudflare, Inc',
    org: 'APNIC and Cloudflare DNS Resolver project',
    as: 'AS13335 Cloudflare, Inc.',
  },
  '8.8.8.8': {
    country: 'United States',
    countryCode: 'US',
    region: 'VA',
    regionName: 'Virginia',
    city: 'Ashburn',
    zip: '20149',
    lat: 39.03,
    lon: -77.5,
    timezone: 'America/New_York',
    isp: 'Google LLC',
    org: 'Google Public DNS',
    as: 'AS15169 Google LLC',
  },
  '172.217.12.132': { // www.google.com
    country: 'United States',
    countryCode: 'US',
    region: 'NY',
    regionName: 'New York',
    city: 'New York',
    zip: '10123',
    lat: 40.7128,
    lon: -74.006,
    timezone: 'America/New_York',
    isp: 'Google LLC',
    org: 'Google LLC',
    as: 'AS15169 Google LLC',
  },
  '/.*/': {
    country: 'United States',
    countryCode: 'US',
    region: 'MA',
    regionName: 'Massachusetts',
    city: 'Boston',
    zip: '02199',
    lat: 42.3487,
    lon: -71.0825,
    timezone: 'America/New_York',
    isp: 'MockServices',
    org: 'MockServices',
    as: 'AS401309 MockServices.',
  },
};
